### ISSUE TITLE
which model could I download?

### ISSUE THREAD

**Issue by cbt12123** [ShineChen1024/oms-Diffusion#104]
I have something wrong:
Traceback (most recent call last):
  File "G:\MagicClothing\inference.py", line 38, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance, False)
  File "G:\MagicClothing\garment_adapter\garment_diffusion.py", line 31, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

I wonder where is "cloth_segm.pth" can be downloaded,which model should be used.
I've downloaded these:
- ip-adapter-faceid-plusv2_sdxl_lora.safetensors
- ip-adapter-faceid-plus_sd15.bin
- ip-adapter-faceid-plusv2_sdxl.bin
- ip-adapter-faceid-portrait_sd15.bin

**Comment by vivi-gomez** [comment]
The cloth_segm.pth is here:
https://huggingface.co/ShineChen1024/MagicClothing/tree/main

> I have something wrong: Traceback (most recent call last): File "G:\MagicClothing\inference.py", line 38, in full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance, False) File "G:\MagicClothing\garment_adapter\garment_diffusion.py", line 31, in **init** with safe_open(ref_path, framework="pt", device="cpu") as f: safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
> 
> I wonder where is "cloth_segm.pth" can be downloaded,which model should be used. I've downloaded these:
> 
>     * ip-adapter-faceid-plusv2_sdxl_lora.safetensors
> 
>     * ip-adapter-faceid-plus_sd15.bin
> 
>     * ip-adapter-faceid-plusv2_sdxl.bin
> 
>     * ip-adapter-faceid-portrait_sd15.bin
