### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by jeffreyrobeson** [ShineChen1024/oms-Diffusion#11]
Traceback (most recent call last):
  File "E:\software\oms-Diffusion\inference.py", line 33, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device)
  File "E:\software\oms-Diffusion\garment_adapter\garment_diffusion.py", line 23, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by OmariNewAeon** [comment]
i have same issue

**Comment by ShineChen1024** [comment]
#5
