### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by hiowenluke** [ShineChen1024/oms-Diffusion#19]
Command line (the files are all exists):
```
python gradio_generate.py --model_path .\examples\model\01008_00.jpg
```

Errors:
```
(oms-diffusion) D:\oms-Diffusion>
Loading pipeline components...: 100%██████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  6.10it/s]
Traceback (most recent call last):
  File "D:\oms-Diffusion\gradio_generate.py", line 20, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device)
  File "D:\oms-Diffusion\garment_adapter\garment_diffusion.py", line 23, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by ShineChen1024** [comment]
#5
