### ISSUE TITLE
Can't loads the local safetensors file 

### ISSUE THREAD

**Issue by hiowenluke** [ShineChen1024/oms-Diffusion#20]
Command line (the files are all exists):
```
python gradio_generate.py --model_path .\examples\model\01008_00.jpg --pipe_path .\checkpoints\RealisticVisionV51.safetensors
```

Errors:
```
Traceback (most recent call last):
  File "D:\oms-Diffusion\gradio_generate.py", line 18, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(args.pipe_path, vae=vae, torch_dtype=torch.float16)
  File "C:\Users\admin\anaconda3\envs\oms-diffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\oms-diffusion\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1096, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\admin\anaconda3\envs\oms-diffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\oms-diffusion\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1656, in download
    info = model_info(pretrained_model_name, token=token, revision=revision)
  File "C:\Users\admin\anaconda3\envs\oms-diffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\admin\anaconda3\envs\oms-diffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '.\checkpoints\RealisticVisionV51.safetensors'.
```

**Comment by ShineChen1024** [comment]
diffusers can load safetensor by different method, or download the folders in huggingface.
