### ISSUE TITLE
请协助解决：safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by wikeeyang** [ShineChen1024/oms-Diffusion#22]
您好！尝试在 windows 环境本地部署：
windows 11 x64、Python 3.10.13、Torch 2.0.1+cu118、其它都安装 readme 里面的指示安装依赖版本。
pip install numpy==1.25.1 diffusers==0.25.1 transformers==4.31.0 gradio==4.16.0 safetensors==0.3.1 controlnet-aux==0.0.6 accelerate==0.21.0
模型文件从 百度网盘 下载的。3个文件都放在 OMSDiffusion\checkpoints 目录下。

执行 python gradio_generate.py --model_path checkpoints/cloth_segm.pth
报错如下：

D:\AITest\OMSDiffusion>python gradio_generate.py --model_path checkpoints/cloth_segm.pth
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.30it/s]
Traceback (most recent call last):
  File "D:\AITest\OMSDiffusion\gradio_generate.py", line 20, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device)
  File "D:\AITest\OMSDiffusion\garment_adapter\garment_diffusion.py", line 23, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

其它模型通过 huggingface snapshot 方式自动下载，存放目录结构如下图：
![目录结构](https://github.com/ShineChen1024/oms-Diffusion/assets/131220899/ba87936c-e980-43a3-80bb-4c9eeb01abe3)

也曾经从 huggingface 模型地址，重新下载过模型文件，依然报错，所以不知如何解决，请指导一下，谢谢！

**Comment by wikeeyang** [comment]
知道了，对 model 没理解到位，谢谢！能够跑起来了，效果还不错！感觉比 OOTDiffusion 更有希望，希望项目取得成功！
