### ISSUE TITLE
报错，求助，试了很多办法。

### ISSUE THREAD

**Issue by kellyvv** [ShineChen1024/oms-Diffusion#51]
2024-04-17 11:52:43.470077: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-17 11:52:43.470129: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-17 11:52:43.471608: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-17 11:52:44.532182: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading pipeline components...: 100% 5/5 [00:03<00:00,  1.59it/s]
Traceback (most recent call last):
  File "/content/MagicClothing/gradio_generate.py", line 25, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance)
  File "/content/MagicClothing/garment_adapter/garment_diffusion.py", line 28, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
OSError: No such device (os error 19)

**Comment by sunhaha123** [comment]
same problem!

**Comment by trikim** [comment]
same problem, have you fixed it?

**Comment by Danny-zhang-xu** [comment]
> 2024-04-17 11:52:43.470077: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered 2024-04-17 11:52:43.470129: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered 2024-04-17 11:52:43.471608: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered 2024-04-17 11:52:44.532182: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT Loading pipeline components...: 100% 5/5 [00:03<00:00, 1.59it/s] Traceback (most recent call last): File "/content/MagicClothing/gradio_generate.py", line 25, in full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance) File "/content/MagicClothing/garment_adapter/garment_diffusion.py", line 28, in **init** with safe_open(ref_path, framework="pt", device="cpu") as f: OSError: No such device (os error 19)

Your cuda and cudnn need to support each other, please note the version issue.

**Comment by KurokyLee** [comment]
I met the same error, but I check my cuda and cudnn version. They are correct. So I still suffer from the error

**Comment by KurokyLee** [comment]
I just fixed it. It seems not to be the cuda or cudnn version mismatch. I read the txt in ./checkpoints the use the correct command and it works! Before you run the python file, you shoule move the cloth_segm.pth to ./checkpoints. Then use command arg --model_path ./checkpoints/magicclothing/early_access/oms_diffusion_768_200000.safetensors
