### ISSUE TITLE
Downloading checkpoints specifically in colab

### ISSUE THREAD

**Issue by AB00k** [ShineChen1024/oms-Diffusion#65]
From where can I download cloth_segm.pth?

And on huggingface I see multiple files which file should I download and place in MagicClothing/checkpoints/ipadapter_faceid?

How can I download these both directly in colab or is there any available implementation on colab?

I know my question are very basic, but I would greatly appreciate any help.

**Comment by ShineChen1024** [comment]
https://huggingface.co/h94/IP-Adapter-FaceID
https://huggingface.co/ShineChen1024/MagicClothing

**Comment by AB00k** [comment]
There are multiple files in https://huggingface.co/h94/IP-Adapter-FaceID, which one should I download?

**Comment by ShineChen1024** [comment]
v2_15

**Comment by AB00k** [comment]
I'm sorry, If i'm bothering you but which model check point path should I pass in following command
!python inference.py --cloth_path [your cloth path] --model_path [your model checkpoints path] --enable_cloth_guidance

**Comment by AB00k** [comment]
Traceback (most recent call last):
  File "/content/MagicClothing/inference.py", line 38, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance, False)
  File "/content/MagicClothing/garment_adapter/garment_diffusion.py", line 31, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by AiTERNA** [comment]
your model path is wrong, I got the same error. download 768 vitonhd safetensors from hugging face and put it to checkpoints folder

**Comment by AB00k** [comment]
I'm using this following command
!python inference.py --cloth_path /content/WTT0236-BLK1.jpg --model_path /content/IP-Adapter-FaceID/ip-adapter-faceid-plusv2_sd15.bin --enable_cloth_guidance


And I have cloned both of the repos: https://huggingface.co/h94/IP-Adapter-FaceID
                                                            https://huggingface.co/ShineChen1024/MagicClothing
                                                            
                                                            
And have tried to put "/content/IP-Adapter-FaceID/ip-adapter-faceid-plusv2_sd15.bin" in "/content/MagicClothing/checkpoints/ipadapter_faceid" and "/content/MagicClothing_/cloth_segm.pth"  inside "/content/MagicClothing/checkpoints" folder and then try to run the command I mentioned above but still have above error.

**Comment by AB00k** [comment]
@AiTERNA  Can you please mention what I might be doing wrong, bellow is the notebook link I'm using if you can have a look I would greatly appreciate it.
https://colab.research.google.com/drive/1MSxlN3UhMq9hm_7ZKGplCs6PSBocWYCT?usp=sharing

**Comment by AiTERNA** [comment]
ip-adapter-faceid-plusv2_sd15.bin is the wrong model I guess, download a safetensor model (vtonhd or dresscode) from huggingface page

**Comment by AB00k** [comment]
@AiTERNA Thanks, it's working now. And is is there a way to make it work with bottom garments.
![image](https://github.com/ShineChen1024/MagicClothing/assets/121571684/12e63e07-1e25-419c-b37a-876049124146)
